retry allocate in all workflows
Signed-off-by: David Fridrich <fridrich.david19@gmail.com>

diff --git a/.github/workflows/test-e2e.yaml b/.github/workflows/test-e2e.yaml
--- a/.github/workflows/test-e2e.yaml
+++ b/.github/workflows/test-e2e.yaml
@@ -19,7 +19,22 @@ jobs:
       - name: Install Binaries
         run: ./hack/install-binaries.sh
       - name: Allocate Cluster
-        run: ./hack/allocate.sh
+        run: |
+          attempt=0
+          max_attempts=5
+          until [ $attempt -ge $max_attempts ]
+          do
+            attempt=$((attempt+1))
+            echo "------------------ Attempt $attempt ------------------"
+            ./hack/allocate.sh && break
+            echo "------------------ failed, retrying... ------------------"
+            if [ $attempt -ge $max_attempts ]; then
+              echo "------------------ max # of retries reached, exiting ------------------"
+              exit 1
+            fi
+            ./hack/delete.sh
+          done
+          echo "------------------ finished! attempt $attempt ------------------"
       - name: Local Registry
         run: ./hack/registry.sh
       - name: E2E Test
